### PR TITLE
Kaitlyn

### PR DESCRIPTION
**Pull request by kmaccc**
I added just the very basics of projection mechanics, creating another instance of the character object at a space of 3 in front of the current player when the space bar is pressed.  I also removed the ability to jump multiple times by checking whether the character is on the ground before they can jump.

### CODE REVIEW

**Comment by thomasythuang** [comment]
Looks great! Just before the merge though, could you delete these two files:
Game.CSharp.csproj
Game.sln

and then push that to your branch again? I think they got past the gitignore, but we also don't want them stored here (I'll fix that)

**Comment by kmaccc** [comment]
Ok how does this look now?

**Comment by thomasythuang** [comment]
Awesome! +1

**Comment by thomasythuang** [comment]
Also I'm going to just merge it now so I can work off of some stuff on it! Looks good though

**Pull request merged**
